INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (999, 1, '001', 'BUDGET')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (998, 1, '002', 'STANDARD')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (997, 1, '003', 'SUPERIOR')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (996, 1, '004', 'STANDARD')

INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (999, 1, '001', 'BUDGET')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (998, 1, '002', 'STANDARD')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (997, 1, '003', 'SUPERIOR')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (996, 1, '004', 'STANDARD')
