INSERT INTO GUEST (ID, EMAIL, NAME, VERSION) VALUES (9999, 'david@zuhause.de', 'David Schmitz', 1)
INSERT INTO GUEST (ID, EMAIL, NAME, VERSION) VALUES (9998, '', 'Dr. Insano', 1)
INSERT INTO GUEST (ID, EMAIL, NAME, VERSION) VALUES (9997, 'kommander@bruka.se', 'Kommandante Brikka', 1)
INSERT INTO GUEST (ID, EMAIL, NAME, VERSION) VALUES (9996, 'bratislaf@metulski.ru', 'Bratislaf Metulski', 1)
INSERT INTO GUEST (ID, EMAIL, NAME, VERSION) VALUES (9995, 'rschmutschen@panama.de', 'Rutschen Schmutschen', 1)


INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (999, 1, '001', 'BUDGET')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (998, 1, '002', 'STANDARD')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (997, 1, '003', 'SUPERIOR')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (996, 1, '004', 'STANDARD')


INSERT INTO RESERVATION (ID, CHECKINDATE, CHECKOUTDATE, RESERVATIONNUMBER, RESERVATIONSTATUS, VERSION, ASSIGNEDROOM_ID, GUEST_ID, COSTSINEURO) VALUES (999, '2013-01-01', '2013-02-01', 'abc-123', 'OPEN', 1, 999, 9999, 242.23)
INSERT INTO RESERVATION (ID, CHECKINDATE, CHECKOUTDATE, RESERVATIONNUMBER, RESERVATIONSTATUS, VERSION, ASSIGNEDROOM_ID, GUEST_ID, COSTSINEURO) VALUES (998, '2014-05-11', '2014-05-12', 'aea-193', 'OPEN', 1, 997, 9998, 1213.56)