INSERT INTO GUEST (ID, EMAIL, NAME, VERSION) VALUES (9999, 'david@zuhause.de', 'David Schmitz', 1)
INSERT INTO GUEST (ID, EMAIL, NAME, VERSION) VALUES (9998, 'kommander@bruka.se', 'Kommandante Brikka', 1)

INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (999, 1, '001', 'BUDGET')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (998, 1, '002', 'STANDARD')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (997, 1, '003', 'SUPERIOR')
INSERT INTO ROOM (ID, VERSION, ROOMNUMBER, ROOMEQUIPMENT) VALUES (996, 1, '004', 'STANDARD')
